version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
        ANDROID_HOME: /opt/android/sdk
        ADB_INSTALL_TIMEOUT: 10
        _JAVA_OPTIONS: '-Xms1024m -Xmx2048m'
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms1024m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout